title: Thi Duyen Do
logo: images/logo.jpg
description: Welcome to my portfolio!

theme: jekyll-theme-minimal

# Navigation links
navigation:
  Home: /home/
  About Me: /about/
  Contact: /contact/
  CV: /cv/
  #Publications: /publications/
  Research: /research/

include: ["assets/style.css"]
